### ISSUE TITLE
[1.12.2] Signed jar causes crashes when Mixin attempts to use classes cross-library

### ISSUE THREAD

**Issue by PROJonYz** [satyrnidae/wolf-armor-and-storage-legacy#165]
I made a modpack on version 1.12.2 where is 100+ mods (for community), i added Wolf Armor and Storage mod to it, but it doesn't seems to work, if i delete it from modpack, then modpack works fine, i dont know what is the problem, so... can some one explain this, or help?

I tried to install older versions like **3.6.4** and **3.5.4** but that doesn't help anything..

I have 16GB of ram, and 6gb is on minecraft, so it's not it..

**I'm doing modpack from one youtuber, that adding 1 mod in every single episode, so i maded modpack from it, cause he's don't linking his modpack "YET", and i wanna just make people happy, that they can play on the same modpack that him, so... ye... At least, i've tryed :D

But still, i know alot things about modpacking, cause i have been making modpacks since 2017, so.. **

![Screenshot_1](https://user-images.githubusercontent.com/67200060/91664310-02062400-eaf7-11ea-8a10-c33b9253190c.png)

**Comment by satyrnidae** [comment]
Hey there,
Exit code 0 is usually used to indicate that everything worked successfully, so I will need a bit more than just the code to investigate.  Can you upload the latest log file and any relevant crash logs to a couple [gists](https://gist.github.com/) and link them here?  Thanks!

**Comment by PROJonYz** [comment]
@satyrnidae 

Here is the log...

[2020-09-16-7.log](https://github.com/satyrnidae/wolfarmor/files/5234688/2020-09-16-7.log)

[23:04:17] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:04:17] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[23:04:17] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[23:04:18] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2854 for Minecraft 1.12.2 loading
[23:04:18] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_51, running on Windows 10:amd64:10.0, installed at D:\Games\runtime\jre-x64
[23:04:24] [main/INFO] [FML]: Searching C:\Users\lyomi\AppData\Roaming\.minecraft\mods for mods
[23:04:24] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Bloodmoon-MC1.12.2-1.5.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:24] [main/WARN] [FML]: The coremod lumien.bloodmoon.asm.LoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in cxlibrary-1.12.1-1.6.1.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod cubex2.cxlibrary.CoreModLoader does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: The coremod CXLibraryCore (cubex2.cxlibrary.CoreModLoader) is not signed!
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Forgelin-1.8.3.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod net.shadowfacts.forgelin.preloader.ForgelinPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: The coremod ForgelinPlugin (net.shadowfacts.forgelin.preloader.ForgelinPlugin) is not signed!
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in InventoryTweaks_1.12.2_1.64dev.151.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod invtweaks.forge.asm.FMLPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in librarianlib-1.12.2-4.21.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod com.teamwizardry.librarianlib.asm.LibLibCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: The coremod LibrarianLib Plugin (com.teamwizardry.librarianlib.asm.LibLibCorePlugin) is not signed!
[23:04:25] [main/INFO] [FML]: Loading tweaker optifine.OptiFineForgeTweaker from OptiFine_1.12.2_HD_U_F5_MOD.jar
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in ParticleFixes-v1.0.2-1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod com.therandomlabs.randompatches.core.RPCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in rats_3.2.13_1.12.2.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod ratscore (com.github.alexthe666.rats.server.asm.RatsPlugin) is not signed!
[23:04:25] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from TimeCore-1.12.2-1.0.1.1.jar
[23:04:25] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from ValkyrienWarfareRevamped_1.12.2_v0.9_alpha_full1.jar
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in wizardry-0.11.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod com.teamwizardry.wizardry.asm.WizardryCorePlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft
[23:04:25] [main/WARN] [FML]: The coremod Wizardry Plugin (com.teamwizardry.wizardry.asm.WizardryCorePlugin) is not signed!
[23:04:25] [main/INFO] [FML]: Loading tweaker org.spongepowered.asm.launch.MixinTweaker from wolfarmor-1.12.2-3.7.1-universal-signed.jar
[23:04:25] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in themidnight_1.12.2_0.3.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.
[23:04:25] [main/WARN] [FML]: The coremod midnight (com.mushroom.midnight.core.MidnightLoadingPlugin) is not signed!
[23:04:25] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLInjectionAndSortingTweaker
[23:04:25] [main/INFO] [LaunchWrapper]: Loading tweak class name optifine.OptiFineForgeTweaker
[23:04:25] [main/INFO] [LaunchWrapper]: Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: java.util.ServiceConfigurationError: org.spongepowered.asm.service.IMixinServiceBootstrap: Provider org.spongepowered.asm.service.modlauncher.MixinServiceModLauncherBootstrap could not be instantiated
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.access$700(ServiceLoader.java:323)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator$2.run(ServiceLoader.java:407)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:409)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.runBootServices(MixinService.java:77)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.<init>(MixinService.java:72)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.getInstance(MixinService.java:92)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.service.MixinService.boot(MixinService.java:102)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinBootstrap.<clinit>(MixinBootstrap.java:76)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at org.spongepowered.asm.launch.MixinTweaker.<init>(MixinTweaker.java:44)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at java.lang.Class.newInstance(Class.java:442)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:98)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.SecurityException: class "org.spongepowered.asm.service.ServiceInitialisationException"'s signer information does not match signer information of other classes in the same package
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.checkCerts(ClassLoader.java:895)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.preDefineClass(ClassLoader.java:665)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.defineClass(ClassLoader.java:758)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.security.AccessController.doPrivileged(Native Method)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getDeclaredConstructors0(Native Method)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.getConstructor0(Class.java:3075)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.Class.newInstance(Class.java:412)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
[23:04:25] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 18 more

**Comment by satyrnidae** [comment]
ty!
looks like this might be a compatibility issue; some other mod is providing the Mixin utility and causing this conflict.  Can you give me a list of the mods you have in your pack?

**Comment by PROJonYz** [comment]
@satyrnidae 

Mod List:

![Screenshot_1](https://user-images.githubusercontent.com/67200060/93512918-b42e5000-f92d-11ea-87d7-9dbb5e60d66d.png)

**Comment by Shadowpudding** [comment]
I have the same problem. I have around 100 mods too. i have some mods that @PROJonYz  uses too. I´m going to test my pack by slowly adding the mods again. I´ll tell you when i find out which mods could be a problem

**Comment by PROJonYz** [comment]
@Shadowpudding 

I know those styles, but i was too lazy to do long invastigation on adding 2-3 mod in pack, but still got some result if i delete couple of mods from there.

Thank you for trying help me!

**Comment by Mattomanx77** [comment]
Crashing with the same error. Of note, I also had Malisis Doors & Core, but I still crash even after removing them. Building a big pack for fun. I did the same for 1.7 but had not had this issue with this mod in that version. Below I've attached an image of my mods folder in addition to the crash log. (Note: this is after I have removed Malisis'
 two mods.)
![Mods](https://user-images.githubusercontent.com/16867938/94979427-8e3da980-04f0-11eb-8fba-e2ae35374aa1.png)
[latest.log](https://github.com/satyrnidae/wolfarmor/files/5320834/latest.log)

**Comment by flikersprigs** [comment]
hey so I'm getting the same error when I try launching a modpack I'm making for a couple of friends and I, there's a lot of mods in mine but 
![image](https://user-images.githubusercontent.com/31713593/95028628-8bb58e00-066f-11eb-8320-f3f1ac12345f.png)
baubles, dimensional doors, iron chest, and jei are the mods we all have in common

**Comment by Shadowpudding** [comment]
I now have another problem. My game tends to freze even if I make a new game file. When I close the game I get Exit code 0 again and that even after I remove the wolfarmor mod. I think the mod may have broken some other mods that use mixin, but I don't know which mods use it. This is currently only a problem on my main launcher, but not on the other I use.

**Comment by NightOps007** [comment]
Contributing to the cause...
MC: 1.12.2
Forge: 14.23.5.2854
Mods: [modlist.txt](https://github.com/satyrnidae/wolfarmor/files/5362906/modlist.txt)
Log: [latest.log](https://github.com/satyrnidae/wolfarmor/files/5362887/latest.log)
There are two more lines in my active game output window that shows the log in real-time:
[21:11:58.129] Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=256m; support was removed in 8.0
[21:11:58.129] Process crashed with exit code 1

**Comment by satyrnidae** [comment]
thanks @NightOps007, that log confir,s that this is probably a mixin issue; #169 should hopefully fix.

**Comment by ziv876** [comment]
I have kinda the same problem but with enigmatica 2 expert modpack I gave the launcher 8 GB of useable ram and it keeps crashing and says exit code 0 like @PROJonYz 
@satyrnidae can you help please?

**Comment by DarkLeGend56** [comment]
I am having problems, exit code 0, and it wont load, i am not greta at code like yall

**Comment by DemonLordDrake** [comment]
hello i have a mod pack  that i made and its got way diffrent mods than yalls and im getting the same thing and i dont know where toget the crash report cause im usiong a normal minecraft launcher

**Comment by DemonLordDrake** [comment]
![image](https://user-images.githubusercontent.com/81474652/112722856-220d9280-8ee2-11eb-8a52-0dd2ebf34ad7.png)

this is my mod list

**Comment by McSasKia** [comment]
> 
> 
> Hey there,
> Exit code 0 is usually used to indicate that everything worked successfully, so I will need a bit more than just the code to investigate. Can you upload the latest log file and any relevant crash logs to a couple [gists](https://gist.github.com/) and link them here? Thanks!

Hey, I've got a similar problem but don't understand log files due to absolutely no knowledge about programming. Could you please help me with what's going wrong? I only have three mods and the game also crashes when I put them out (I can start the game normally over the Minecraft launcher but not over CurseForge).
Thanks in advance
![grafik](https://user-images.githubusercontent.com/81981823/113599887-8bf30e00-963f-11eb-96a8-cde37497c17e.png)

**Comment by satyrnidae** [comment]
Attempting a fix by un-bundling Mixin.

**Comment by satyrnidae** [comment]
hrm wait nope
It was a signing issue. Likely some other mod also loaded mixin and some of the classes in that mod's version of mixin were signed differently.
